**Ejercicio 3.** Sean $R_1$ y $R_2$ relaciones en $A×B$ y $B×C$, respectivamente, donde $A=\{a_1,a_2,a_3,a_4\}, B=\{b_1,b_2,b_3\}$ y $C=\{c_1,c_2,c_3,c_4\}$.

1. Construye las relaciones $R_1$ y $R_2$ de forma aleatoria. (Utiliza por ejemplo la función random() de Python.)
2. Calcula la composición min-max R1∙R2 y escribir en forma matricial.
3. Calcula la composición max-min R1∘R2 y escribir en forma matricial.
4. Escribe R1∙R2 y R1∘R2 utilizando la notación de Zadeh para conjuntos difusos.
5. Escribe en notación de Zadeh la proyección de R1∙R2 en A.
6. Escribe en notación de Zadeh la proyección de R1∘R2 en C.

In [22]:
import random
import numpy as np

def maxmincomposition(X,Y):
    C = np.zeros((X.shape[0],Y.shape[1]))
    # Iterar a traves de las filas de A
    for i in range(len(X)):
       # Iterar a traves de las columnas de B
       for j in range(len(Y[0])):
           # Iterar a traves de las filas de B
           for k in range(len(Y)):
                if(np.minimum(X[i][k], Y[k][j]) > C[i][j]):
                    C[i][j] =  np.minimum(X[i][k], Y[k][j])
    return C

def minmaxcomposition(X,Y):
    C = np.ones((X.shape[0],Y.shape[1]))
    # Iterar a traves de las filas de A
    for i in range(len(X)):
       # Iterar a traves de las columnas de B
       for j in range(len(Y[0])):
           # Iterar a traves de las filas de B
           for k in range(len(Y)):
                if(np.maximum(X[i][k], Y[k][j]) < C[i][j]):
                    C[i][j] =  np.maximum(X[i][k], Y[k][j])
    return C

def generaraleatorios(X):
    for i,j in np.ndindex(X.shape):
            X[i][j] = round(random.uniform(0, 1),1)   
    return X

R1 = np.zeros((4,3))

R1 = generaraleatorios(R1)

R2 = np.zeros((3,4))

R2 = generaraleatorios(R2)

print("Dada la matriz R1")
print(R1)
print("Dada la matriz R2")
print(R2)
print("La composicion min-max tiene como resultado:")
print(minmaxcomposition(R1,R2))
print("La composicion max-min tiene como resultado:")
print(maxmincomposition(R1,R2))

Dada la matriz R1
[[0.8 0.8 0.3]
 [0.6 0.2 0.9]
 [0.7 0.7 0.4]
 [0.8 0.2 0.7]]
Dada la matriz R2
[[0.1 0.7 0.6 0.2]
 [1.  0.4 0.7 1. ]
 [0.5 0.4 0.9 0.9]]
La composicion min-max tiene como resultado:
[[0.5 0.4 0.8 0.8]
 [0.6 0.4 0.6 0.6]
 [0.5 0.4 0.7 0.7]
 [0.7 0.4 0.7 0.8]]
La composicion max-min tiene como resultado:
[[0.8 0.7 0.7 0.8]
 [0.5 0.6 0.9 0.9]
 [0.7 0.7 0.7 0.7]
 [0.5 0.7 0.7 0.7]]


Dadas las relaciones difusas $R_1$ ∶ $A × B$ → $[0, 1]$ y $R_2$ ∶ $B × C$ → $[0, 1]$. Entonces, la composicion max–min $R = R_1 ∙ R_2$ es una relacion difusa en $A$ y $C$ definido por:

$R(a, c) = \max_{b ∈ B} min[R_1(a, b), R_2(b, c)].$

Dadas las relaciones difusas $R_1$ ∶ $A × B$ → $[0, 1]$ y $R_2$ ∶ $B × C$ → $[0, 1]$. Entonces, la composicion max–min $R = R_1 ∘ R_2$ es una relacion difusa en $A$ y $C$ definido por:

$R(a, c) = \min_{b ∈ B} max[R_1(a, b), R_2(b, c)].$

$Proj_A R_1 ∙ R_2 = sup_{y ∈ B X C} A(x,y)$

$Proj_C R_1 ∘ R_2 = sup_{y ∈ A X B} C(x,y)$