# __Ejercitario 3__: Relaciones Difusas

Responde a las preguntas de abajo utilizando este mismo notebook. Recuerda de seguir las instrucciones de envío que están en la plataforma Educa.

---
**Ejercicio 1.** En el texto de Bede (2013) lee la Definición 3.19 (p.38) de la composición $\min\!\!\to$ entre dos relaciones $R$ y $S$, denotado $R \lhd S$, y su operación dual $R\rhd S$. Demuestra que:

1. $(R\lhd S) = (S^{-1}\rhd R^{-1})^{-1}$.
2. $(R\rhd S) = (S^{-1} \lhd R^{-1})^{-1}$.

1. Teniendo en cuenta que $R \in \mathcal{F}(X\times Y)$ y $S \in \mathcal{F}(Y\times Z)$

>$(S^{-1}\rhd R^{-1})^{-1}(x, z)=(S^{-1}\rhd R^{-1})(z, x)=S^{-1}(z, y)\rhd R^{-1}(y, x)=\bigwedge_{y \in Y} R(x, y) \to S(y, z)=R\lhd S(x, z)$

Por lo tanto, queda demostrado.

2. De vuelta, teniendo en cuenta que $R \in \mathcal{F}(X\times Y)$ y $S \in \mathcal{F}(Y\times Z)$

>$(S^{-1}\lhd R^{-1})^{-1}(x, z)=(S^{-1}\lhd R^{-1})(z, x)=S^{-1}(z, y)\lhd R^{-1}(y, x)=\bigwedge_{y \in Y} S(y, z)\to R(x, y)=R\rhd S(x, z)$

Por lo tanto, queda demostrado.

---
**Ejercicio 2.** Escribe una subrutina que tome como entrada dos matrices representando relaciones difusas $R$ y $S$ y retorne (o imprima en pantalla) $R\lhd S$. Escribe al menos dos ejemplos diferentes que muestren como funciona tu algoritmo. Puedes elegir tu lenguaje de programación favorito para este ejercicio.

In [145]:
def function(R,S):
    for r_row in range(len(R)):
        for s_column in range(len(S[0])):
            greatest=0
            row=0
            for x in R[r_row]:
                s_row=S[row]
                if x<=s_row[s_column]:
                    value=1
                else:
                    value=s_row[s_column]
                if value>greatest:
                    greatest=value
                row+=1
            if greatest==1:
                print("  1",end="   ")
            else:
                print(greatest, end="   ")
        print()
    
R=[
[0.2, 0.8, 0.9],
[0.9, 0.4, 0.7],
[0.5, 0.7, 0.4],
[0.6, 0.9, 0.2]
]

S=[
[0.9, 0.5, 0.3, 0.4, 0.8],
[0.7, 0.1, 0.4, 0.2, 0.3],
[0.5, 0.6, 0.2, 0.1, 0.9]
]

R2=[
[0.7, 0.5, 0.4],
[0.5, 0.8, 0.9]
]

S2=[
[0.3, 0.8, 0.4, 0.5, 0.6],
[0.1, 0.7, 0.7, 0.2, 0.1],
[0.2, 0.3, 0.2, 0.4, 0.3]
]


print("R ⊲ S")
function(R,S)
print()
print("R2 ⊲ S2")
function(R2,S2)


R ⊲ S
  1     1     1     1     1   
  1   0.6     1   0.4     1   
  1     1   0.4   0.4     1   
  1     1     1   0.4     1   

R2 ⊲ S2
0.3     1     1     1   0.6   
0.3     1   0.7     1     1   


---
**Ejercicio 3.** Escribe una subrutina que tome como entrada dos matrices representando relaciones difusas $R$ y $S$ y retorne (o imprima en pantalla) $R\rhd S$. Escribe al menos dos ejemplos diferentes que muestren como funciona tu algoritmo. Puedes elegir tu lenguaje de programación favorito para este ejercicio.

In [27]:
import numpy as np

def godel_implication(x, y):
    if (x <= y):
        return 1
    else:
        return y

def supercomposition(R, S):
    result = np.ones( (len(S), len(R[0])) )
    for i in range(len(S)):
        for j in range(len(R[0])):
            for k in range(len(R)):
                result[i][j] = np.minimum(result[i][j],  godel_implication(S[i][k], R[k][j]))
    return result

R = np.array([[0.3, 0.7, 0.2],
            [1, 0, 0.9]])

S = np.array([[0.8, 0.3],
            [0.1, 0],
            [0.5, 0.6]])

print(supercomposition(R, S), '\n')

R = np.array([[0.5, 0.2],
             [0.3, 1]])

S = np.array([[0.8, 0.1],
             [0.3, 0.4]])

print(supercomposition(R, S))

[[0.3 0.  0.2]
 [1.  1.  1. ]
 [0.3 0.  0.2]] 

[[0.5 0.2]
 [0.3 0.2]]


---
**Ejercicio 4.** Sean $R:X\times Y\to [0,1]$, $P:Y\times Z\to [0,1]$ y $Q:X\times Z\to[0,1]$ relaciones difusas. Demuestra que $(P\lhd Q^{-1})^{-1}\circ P\subseteq Q$.

Usando (v) de la Proposición 3.18 del libro de Bede tenemos:

$(P\lhd Q^{-1})^{-1}(y, z)\circ P=(P\lhd Q^{-1})(z, y)\circ P=\bigvee_{y \in Y}(P\lhd Q^{-1})(z, y)\wedge P(y, z)=\bigvee_{y \in Y} \bigwedge_{t \in Z}(P(y, t)\to Q(t, x)) \wedge P(y, z) \leq \bigvee_{y \in Y} (P(y, z)\to Q(z, x)) \wedge P(y, z) \leq \bigvee_{y \in Y} Q(x, z)= Q(x, z)$

---
**Ejercicio 5.** Implementa el algoritmo de la $*$-clausura transitiva de la página 83 del libro de Syropoulos & Grammenos (2020). Modifica el algoritmo para que utilice la composición $\min\!\!\to$. Tu algoritmo debe de tomar como entrada una matriz que represente una relación difusa y retornar otra matriz que represente la $*$-clausura transitiva. Escribe al menos dos ejemplos diferentes que muestren como funciona tu algoritmo. Puedes elegir tu lenguaje de programación favorito para este ejercicio.

In [28]:
import numpy as np

def godel_tnorm(a, b):
    return np.minimum(a, b)

def floyd_transitive_closure(R):
    Aux = np.copy(R)
    for i in range(len(Aux)):
        for j in range(len(Aux)):
            for k in range(len(Aux)):
                Aux[j][k] = np.maximum(Aux[j][k],  godel_tnorm(Aux[j][i], Aux[i][k]))
    return Aux

R = np.array([[0.5, 0.2, 0.7],
             [0.3, 1, 0.5],
             [0.2, 0.6, 1]])

result = floyd_transitive_closure(R)

print(result, '\n')

S = np.array([[0.8, 0.1, 1],
             [0.3, 0.4, 0.7],
             [0.4, 0.9, 0.1]])

result = floyd_transitive_closure(S)

print(result, '\n')

[[0.5 0.6 0.7]
 [0.3 1.  0.5]
 [0.3 0.6 1. ]] 

[[0.8 0.9 1. ]
 [0.4 0.7 0.7]
 [0.4 0.9 0.7]] 



---
**Ejercicio 6.** Implementa una subrutina que toma como entrada una matriz que represente una relación difusa y retorna 1 si la matriz es una relación de similaridad y retorna 0 si no es una relación de similaridad. Escribe al menos dos ejemplos diferentes que muestren como funciona tu algoritmo. Puedes elegir tu lenguaje de programación favorito para este ejercicio.

In [33]:
#A fuzzy binary relation in A that is 
    #reflexive, 
    #symmetric, and
    #transitive 
#is a similarity relation in A.
A=[
    [  1, 0.2, 0.4, 0.3, 0.1],
    [0.2,   1, 0.6, 0.7, 0.8],
    [0.4, 0.6,   1, 0.5, 0.2],
    [0.3, 0.7, 0.5,   1, 0.7],
    [0.1, 0.8, 0.2, 0.7,   1]
]

B=[
    [  1, 0.2,   1, 0.6, 0.2, 0.6],
    [0.2,   1, 0.2, 0.2, 0.8, 0.2],
    [  1, 0.2,   1, 0.6, 0.2, 0.6],
    [0.6, 0.2, 0.6,   1, 0.2, 0.8],
    [0.2, 0.8, 0.2, 0.2,   1, 0.2],
    [0.6, 0.2, 0.6, 0.8, 0.2,   1]
]

def function(A):
    #¿Es reflexiva?
    for row in range(len(A)):
        if A[row][row]!=1:
            print(" No es reflexiva")
            return 0
    print(" Es reflexiva")

    #¿Es simétrica?
    row_counter=0
    for row in A:
        #print("row_counter es ",row_counter)
        position=row_counter
        for column in range(row_counter,len(A)):
            #print(row[position],A[position][row_counter])
            if row[position]!=A[position][row_counter]:
                print(" No es simétrica")
                return 0
            position+=1
        row_counter+=1
    print(" Es simétrica")
    
    #¿Es transitiva?
    for a in range(len(A)):
        for c in range(len(A)):
            for b in range(len(A)):
                if A[a][b]<A[b][c]:
                    min_value=A[a][b]
                else:
                    min_value=A[b][c]
                if A[a][c]<min_value:
                    #print("a,b,c", (a,b,c))
                    #print(" No es transitiva porque ",A[a][c], "es menor a", min_value)
                    print(" No es transitiva")
                    return 0
    print(" Es transitiva")
    return 1
            
            
print("La función retorna 1 si la matriz es una relación de similaridad, 0 si no.")
print()
print("Matriz A ...")
print("A: ", function(A))
print()
print("Matriz B ...")

print("B: ", function(B))

La función retorna 1 si la matriz es una relación de similaridad, 0 si no.

Matriz A ...
 Es reflexiva
 Es simétrica
 No es transitiva
A:  0

Matriz B ...
 Es reflexiva
 Es simétrica
 Es transitiva
B:  1


---
**Ejercicio 7.** Implementa una subrutina que toma como entrada una matriz que represente una relación difusa y retorna 1 si la matriz es una relación de proximidad y retorna 0 si no es una relación de proximidad. Escribe al menos dos ejemplos diferentes que muestren como funciona tu algoritmo. Puedes elegir tu lenguaje de programación favorito para este ejercicio.

In [34]:
#¿Es reflexiva?
def reflexiva(A):
    for row in range(len(A)):
        if A[row][row]!=1:
            return 0
    return 1

#¿Es simétrica?
def simetrica(A):
    row_counter=0
    for row in A:
        #print("row_counter es ",row_counter)
        position=row_counter
        for column in range(row_counter,len(A)):
            #print(row[position],A[position][row_counter])
            if row[position]!=A[position][row_counter]:
                return 0
            position+=1
        row_counter+=1
    return 1

def proximidad(A):
    if((reflexiva(A) == 1) & (simetrica(A) == 1)):
        return 1
    return 0

A=[
    [  1, 0.2, 0.4, 0.3, 0.1],
    [0.2,   1, 0.6, 0.7, 0.8],
    [0.4, 0.6,   1, 0.5, 0.2],
    [0.3, 0.7, 0.5,   1, 0.7],
    [0.1, 0.8, 0.2, 0.7,   1]
]

print(proximidad(A))

B=[
    [  1, 0.2,   1, 0.6, 0.2, 0.6],
    [0.2,   1, 0.2, 0.2, 0.8, 0.2],
    [  1, 0.2,   1, 0.6, 0.2, 0.6],
    [0.6, 0.2, 0.6,   1, 0.2, 0.8],
    [0.2, 0.8, 0.2, 0.2,   1, 0.2],
    [0.6, 0.2, 0.6, 0.8, 0.2,   1]
]

print(proximidad(B))

1
1


---
**Ejercicio 8.** Construye un ejemplo concreto de una relación difusa $R:A\times A\to[0,1]$ infinita que sea reflexiva, simétrica pero no sea transitiva.

$\frac{a_{11}}{x_1,y_1}+\frac{\displaystyle a_{12}}{\displaystyle x_1,y_2}+...+\frac{\displaystyle a_{1n}}{\displaystyle x_1,y_n}+\frac{\displaystyle a_{21}}{\displaystyle x_2,y_1}+\frac{\displaystyle a_{22}}{\displaystyle x_2,y_2}+...+\frac{\displaystyle a_{2n}}{\displaystyle x_2,y_n}+...+\frac{\displaystyle a_{n1}}{\displaystyle x_n,y_1}+\frac{\displaystyle a_{n2}}{\displaystyle x_n,y_2}+...+\frac{\displaystyle a_{nn}}{\displaystyle x_n,y_n}$

$donde\;para\;todo\;x_k,y_k\;se\;tiene\;a_{kk}=1\;$

$donde\;para\;todo\;x_i,y_j\;e\;i<j\;existe\;un\;par\;x_j,y_i\;tal\;que\;a_{ij}=a_{ji}=\frac1{i\times j}$

$i,j,k\in A$

La matriz se vería de esta manera:
$\begin{array}{l}\begin{vmatrix}1&\frac12&\frac13&\frac14&\frac15&\frac16\;...\\\frac12&1&\frac16&\frac18&\frac1{10}&\frac1{12}\;\;\;\;\;\\\frac13&\frac16&1&\frac1{12}&\frac1{15}&\frac1{18}\;\;\;\;\;\\\frac14&\frac18&\frac1{12}&1&\frac1{20}&\frac1{24}\;\;\;\;\;\\\frac15&\frac1{10}&\frac1{15}&\frac1{20}&1&\frac1{30}\;\;\;\;\;\\\begin{array}{l}\frac16\\...\end{array}&\begin{array}{l}\frac1{12}\\\end{array}&\begin{array}{l}\frac1{18}\\\end{array}&\begin{array}{l}\frac1{24}\\\end{array}&\begin{array}{l}\frac1{30}\\\end{array}&\begin{array}{l}1\;\\\;\;\;\;...\end{array}\end{vmatrix}\\\end{array}$

$Vemos\;claramente\;que\;la\;matriz\;de\;esta\;relación\;es\;simétrica\;y\;reflexiva.$

$Vemos\;que\;para\;a=2\;,b=1\;y\;c=3\;tenemos:$

>$min\left\{R(a,b),R(b,c)\right\}=min\left\{R(2,1),R(1,3)\right\}=min\left\{\frac12,\frac13\right\}=\frac13$
>
>$R(a,c)=R(2,3)=\frac16$

$Como\;R(a,c)<min\left\{R(a,b),R(b,c)\right\}\;se\;observa\;que\;no\;se\;cumple\;la\;propiedad\;transtiva.$

$Por\;ende\;esta\;relación\;difusa\;no\;es\;transitva.$

---
**Ejercicio 9.** Construye un ejemplo concreto de una relación difusa $R:A\times A\to[0,1]$ infinita que sea simétrica, transitiva pero no sea reflexiva.

Definamos una matriz $A\times A$ donde $A$ es un conjunto infinito. Los elementos de la matriz, a partir del $a_{33}$ se van repitiendo de la siguiente forma hasta el infinito:

>$\begin{pmatrix}
    0.9 & 0.2 & 0.1 & 0.9 & \dots\\
    0.2 & 0.8 & 0.1 & 0.2\\
    0.1 & 0.1 & 0.7 & 0.1\\
    0.9 & 0.2 & 0.1 & 0.9\\
    \vdots & & & & \ddots
    \end{pmatrix}
$

Podemos ver facilmente que la relación es simétrica ya que para todo $a, b \in A$ se cumple que $R(a, b)=R(b, a)$. Por ejemplo, $R(2, 1)=R(1, 2)=0.2$. Dicho de otra forma, podemos ver que los elementos arriba y abajo de la diagonal son todos los mismos.

Si hacemos la operación $R \circ R$ (hasta el elemento $a_{33}$ debido a que es imposible hacer esta operación en una matriz infinita) nos resultará la misma matriz $R$, por lo que se cumple la propiedad de transitividad: se cumple que $R \circ R	\subseteq R$ ya que un conjunto es subconjunto de si mismo.

Es facil ver también que la relación no es reflexiva. Ningun elemento de la diagonal principal es 1, cuando todos deberian de serlo. Por lo que se viola la propiedad reflexiva: $R(a, a)=1$ para todo $a \in A$.

---
**Ejercicio 10.** Construye un ejemplo concreto de una relación difusa $R:A\times A\to[0,1]$ infinita que sea reflexiva, transitiva pero no sea simétrica.

Definamos una matriz $A\times A$ donde $A$ es un conjunto infinito. Los elementos de la matriz, a partir del $a_{33}$ se van repitiendo de la siguiente forma hasta el infinito:

$R:AxA=$
$\begin{pmatrix}
    1 & 0.2 & 0.3 & 1 & 0.2 & \dots\\
    0.2 & 1 & 0.3 & 0.2 & 0.1\\
    0.2 & 0.2 & 1 & 0.2 & 0.2\\
    0.1 & 0.2 & 0.3 & 1 &0.2\\
    0.2 & 1 & 0.3 & 0.2 &1\\
    \vdots & & & & & \ddots
    \end{pmatrix}
$

Se ve claramente que la relación es reflexiva, ya que la diagonal principal está compuesta por unos.

También se observa que $a_{13}\neq a_{31};\;\;0.3\neq0.2$, por lo tanto la relación no es simetrica.

Si hacemos la operación $R \circ R$ (hasta el elemento $a_{55}$ debido a que es imposible hacer esta operación en una matriz infinita) se cumple la propiedad de transitividad: $R \circ R	\subseteq R$, por lo tanto la relación es transitiva.
